// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

type Market struct {
	ID                 string                `json:"id"`
	Question           string                `json:"question"`
	Description        string                `json:"description"`
	Outcomes           json.RawMessage       `json:"outcomes"`
	UmaBond            string                `json:"uma_bond"`
	UmaReward          string                `json:"uma_reward"`
	QuestionID         sql.NullString        `json:"question_id"`
	ConditionID        sql.NullString        `json:"condition_id"`
	ClobTokenIds       pqtype.NullRawMessage `json:"clob_token_ids"`
	PendingDeployment  bool                  `json:"pending_deployment"`
	Deploying          bool                  `json:"deploying"`
	DeployingTimestamp sql.NullTime          `json:"deploying_timestamp"`
	DeployedTimestamp  sql.NullTime          `json:"deployed_timestamp"`
}
