// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Deployment struct {
	QuestionID    string `json:"question_id"`
	ConditionID   string `json:"condition_id"`
	PositionIDYes string `json:"position_id_yes"`
	PositionIDNo  string `json:"position_id_no"`
	Status        string `json:"status"`
}
