// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Market struct {
	MarketID           string                `json:"market_id"`
	QuestionID         sql.NullString        `json:"question_id"`
	ConditionID        sql.NullString        `json:"condition_id"`
	ClobTokenIds       pqtype.NullRawMessage `json:"clob_token_ids"`
	PendingDeployment  bool                  `json:"pending_deployment"`
	Deploying          bool                  `json:"deploying"`
	DeployingTimestamp sql.NullTime          `json:"deploying_timestamp"`
	DeployedTimestamp  sql.NullTime          `json:"deployed_timestamp"`
}
