// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const getMarketByID = `-- name: GetMarketByID :one
SELECT market_id, question_id, condition_id, clob_token_ids, pending_deployment, deploying, deploying_timestamp, deployed_timestamp
FROM markets
WHERE market_id = $1
`

func (q *Queries) GetMarketByID(ctx context.Context, marketID string) (Market, error) {
	row := q.db.QueryRowContext(ctx, getMarketByID, marketID)
	var i Market
	err := row.Scan(
		&i.MarketID,
		&i.QuestionID,
		&i.ConditionID,
		&i.ClobTokenIds,
		&i.PendingDeployment,
		&i.Deploying,
		&i.DeployingTimestamp,
		&i.DeployedTimestamp,
	)
	return i, err
}

const setMarketDeployed = `-- name: SetMarketDeployed :exec
UPDATE markets
SET deploying = FALSE,
    pending_deployment = FALSE,
    deployed_timestamp = NOW(),
    question_id = $2,
    condition_id = $3,
	clob_token_ids = $4
WHERE market_id = $1
`

type SetMarketDeployedParams struct {
	MarketID     string                `json:"market_id"`
	QuestionID   sql.NullString        `json:"question_id"`
	ConditionID  sql.NullString        `json:"condition_id"`
	ClobTokenIds pqtype.NullRawMessage `json:"clob_token_ids"`
}

func (q *Queries) SetMarketDeployed(ctx context.Context, arg SetMarketDeployedParams) error {
	_, err := q.db.ExecContext(ctx, setMarketDeployed,
		arg.MarketID,
		arg.QuestionID,
		arg.ConditionID,
		arg.ClobTokenIds,
	)
	return err
}

const setMarketDeploying = `-- name: SetMarketDeploying :exec
UPDATE markets
SET deploying = TRUE,
	pending_deployment = FALSE,
    deploying_timestamp = NOW()
WHERE market_id = $1
`

func (q *Queries) SetMarketDeploying(ctx context.Context, marketID string) error {
	_, err := q.db.ExecContext(ctx, setMarketDeploying, marketID)
	return err
}

const setMarketPendingDeployment = `-- name: SetMarketPendingDeployment :exec
UPDATE markets
SET pending_deployment = TRUE
WHERE market_id = $1
`

func (q *Queries) SetMarketPendingDeployment(ctx context.Context, marketID string) error {
	_, err := q.db.ExecContext(ctx, setMarketPendingDeployment, marketID)
	return err
}
