// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	GetMarketByID(ctx context.Context, id string) (Market, error)
	SetMarketDeployed(ctx context.Context, arg SetMarketDeployedParams) error
	SetMarketDeploying(ctx context.Context, id string) error
	SetMarketPendingDeployment(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
