// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error
	GetDeploymentStatus(ctx context.Context, questionID string) (string, error)
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error
}

var _ Querier = (*Queries)(nil)
