// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package database

import (
	"context"
)

const createDeployment = `-- name: CreateDeployment :exec
INSERT INTO deployments (question_id, condition_id, position_id_yes, position_id_no, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateDeploymentParams struct {
	QuestionID    string `json:"question_id"`
	ConditionID   string `json:"condition_id"`
	PositionIDYes string `json:"position_id_yes"`
	PositionIDNo  string `json:"position_id_no"`
	Status        string `json:"status"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, createDeployment,
		arg.QuestionID,
		arg.ConditionID,
		arg.PositionIDYes,
		arg.PositionIDNo,
		arg.Status,
	)
	return err
}

const getDeploymentStatus = `-- name: GetDeploymentStatus :one
SELECT status
FROM deployments
WHERE question_id = $1
`

func (q *Queries) GetDeploymentStatus(ctx context.Context, questionID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentStatus, questionID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = $2
WHERE question_id = $1
`

type UpdateDeploymentStatusParams struct {
	QuestionID string `json:"question_id"`
	Status     string `json:"status"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.QuestionID, arg.Status)
	return err
}
