// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const getMarketByID = `-- name: GetMarketByID :one
SELECT id, question, description, outcomes, question_id, condition_id, clob_token_ids, pending_deployment, deploying, deploying_timestamp, deployed_timestamp
FROM markets
WHERE id = $1
`

func (q *Queries) GetMarketByID(ctx context.Context, id string) (Market, error) {
	row := q.db.QueryRowContext(ctx, getMarketByID, id)
	var i Market
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Description,
		&i.Outcomes,
		&i.QuestionID,
		&i.ConditionID,
		&i.ClobTokenIds,
		&i.PendingDeployment,
		&i.Deploying,
		&i.DeployingTimestamp,
		&i.DeployedTimestamp,
	)
	return i, err
}

const setMarketDeployed = `-- name: SetMarketDeployed :exec
UPDATE markets
SET deploying = FALSE,
    pending_deployment = FALSE,
    deployed_timestamp = $2,
    question_id = $3,
    condition_id = $4,
	clob_token_ids = $5
WHERE id = $1
`

type SetMarketDeployedParams struct {
	ID                string                `json:"id"`
	DeployedTimestamp sql.NullTime          `json:"deployed_timestamp"`
	QuestionID        sql.NullString        `json:"question_id"`
	ConditionID       sql.NullString        `json:"condition_id"`
	ClobTokenIds      pqtype.NullRawMessage `json:"clob_token_ids"`
}

func (q *Queries) SetMarketDeployed(ctx context.Context, arg SetMarketDeployedParams) error {
	_, err := q.db.ExecContext(ctx, setMarketDeployed,
		arg.ID,
		arg.DeployedTimestamp,
		arg.QuestionID,
		arg.ConditionID,
		arg.ClobTokenIds,
	)
	return err
}

const setMarketDeploying = `-- name: SetMarketDeploying :exec
UPDATE markets
SET deploying = TRUE,
	pending_deployment = FALSE,
    deploying_timestamp = NOW()
WHERE id = $1
`

func (q *Queries) SetMarketDeploying(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setMarketDeploying, id)
	return err
}

const setMarketPendingDeployment = `-- name: SetMarketPendingDeployment :exec
UPDATE markets
SET pending_deployment = TRUE
WHERE id = $1
`

func (q *Queries) SetMarketPendingDeployment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setMarketPendingDeployment, id)
	return err
}
